stages: [build, deploy]

variables:
  FRONT_DST: "/var/www/petshop-frontend"
  GIT_CLEAN_FLAGS: "-ffdx -e node_modules" 
  
build_front:
  stage: build
  tags: [oracle]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "gitlab"'
    - if: '$CI_COMMIT_BRANCH == "devops"'
  script:
    - docker buildx build --target build --output type=local,dest=dist .

  artifacts:
    paths: [dist]
    expire_in: 1 week

deploy_front:
  stage: deploy
  tags: [oracle]
  needs: [build_front]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "gitlab"'
    - if: '$CI_COMMIT_BRANCH == "devops"'
  script:
    - mkdir -p "$FRONT_DST"
    - rsync -a --delete dist/ "$FRONT_DST"/
