stages: [build, deploy]

variables:
  FRONT_DST: "/var/www/petshop-frontend"
  BUILD_IMAGE: "petshop-frontend-build:$CI_COMMIT_SHORT_SHA"
  GIT_CLEAN_FLAGS: "-ffdx -e node_modules"   
  
build_front:
  stage: build
  tags: [oracle]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "gitlab"'
    - if: '$CI_COMMIT_BRANCH == "devops"'
  script:
    - >
      docker run --rm -v "$CI_PROJECT_DIR":/w busybox
      sh -c '
        if [ -d /w/node_modules ]; then
          chmod -R u+w /w/node_modules 2>/dev/null || true;
          rm -rf /w/node_modules 2>/dev/null || true;
        fi
      '

    - docker build --target build -t "$BUILD_IMAGE" .

    - export HOST_UID=$(id -u) HOST_GID=$(id -g)
    - mkdir -p dist
    - >
      docker run --rm
      -u $HOST_UID:$HOST_GID
      -v "$CI_PROJECT_DIR/dist":/out
      "$BUILD_IMAGE"
      sh -lc 'cp -a /app/dist/. /out/'

  artifacts:
    paths: [dist]
    expire_in: 1 week

deploy_front:
  stage: deploy
  tags: [oracle]
  needs: [build_front]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "gitlab"'
    - if: '$CI_COMMIT_BRANCH == "devops"'
  script:
    - mkdir -p "$FRONT_DST"
    - rsync -a --delete dist/ "$FRONT_DST"/
