stages: [build, deploy]

variables:
  FRONT_DST: "/var/www/petshop-frontend"

build_front:
  stage: build
  tags: [oracle]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "gitlab"'
  script:
    - docker run --rm -v "$CI_PROJECT_DIR":/app -w /app node:20-alpine sh -lc '
        set -e
        if [ -f package-lock.json ]; then npm ci --no-audit --fund=false; else npm i --no-audit --fund=false; fi
        NODE_ENV=production npx vite build
      '
  artifacts:
    paths: [dist]
    expire_in: 1 week

deploy_front:
  stage: deploy
  tags: [oracle]
  needs: [build_front]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "gitlab"'
  script:
    - mkdir -p "$FRONT_DST"
    - rsync -a --delete dist/ "$FRONT_DST"/
