stages: [build, deploy]

variables:
  FRONT_DST: "/var/www/petshop-frontend"
  BUILD_IMAGE: "petshop-frontend-build:$CI_COMMIT_SHORT_SHA"

build_front:
  stage: build
  tags: [oracle]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "gitlab"'
    - if: '$CI_COMMIT_BRANCH == "devops"'
  script:
    - export HOST_UID=$(id -u) HOST_GID=$(id -g)
    - >
      docker run --rm -v "$CI_PROJECT_DIR":/work alpine:3.20
      sh -lc "rm -rf /work/node_modules || true; chown -R $HOST_UID:$HOST_GID /work || true"

    - docker build --target build -t "$BUILD_IMAGE" .

    - mkdir -p dist
    - >
      docker run --rm
      -u $HOST_UID:$HOST_GID
      -v "$CI_PROJECT_DIR/dist":/out
      "$BUILD_IMAGE"
      sh -lc 'cp -a /app/dist/. /out/'

  artifacts:
    paths: [dist]
    expire_in: 1 week

deploy_front:
  stage: deploy
  tags: [oracle]
  needs: [build_front]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "gitlab"'
    - if: '$CI_COMMIT_BRANCH == "devops"'
  script:
    - mkdir -p "$FRONT_DST"
    - rsync -a --delete dist/ "$FRONT_DST"/
